### ISSUE TITLE
reactor doesnt allow thermal fluids

### ISSUE THREAD

**Issue by RogueLogix** [BiggerSeries/BiggerReactors#1]
thermal fluids don't exist in 1.15.2+ yet as of writing. 

if you googled for this issue, update your version or add them in the config, its probably supported in the latest version if the thermal fluids exist

**Comment by Xious01** [comment]
biggerreactors-1.18.2-0.6.0-beta.1.1 Thermal fluid wont work. I understand it is in beta.

**Comment by RogueLogix** [comment]
Thermal 1.19.2 added fluids back, next 1.19.2 version will have support

**Comment by RogueLogix** [comment]
added back in 1.19.2-0.6.0-beta.6
