### ISSUE TITLE
Rednet port and CC:TW is broken in 0.5.0

### ISSUE THREAD

**Issue by lumi-jay** [BiggerSeries/BiggerReactors#13]
I guess the peripherals name got changed between 0.4 and 0.5 - now all my CC:TW codes are broken- I had to downgrade back to 0.4 for the time being, hopefully you can revert back to the old name. Periphal name from the rednet port is different from 0.4, resulting in broken codes on multiple CC systems.

**Comment by RogueLogix** [comment]
The cc:t integration had a massive overhaul in 0.5.0 to match the mechanic changes made, you will need to update your computer scripts to match.

**Comment by lumi-jay** [comment]
where can I find the BiggerReactors API ?
