### ISSUE TITLE
Reactor gets disconnected from Computercraft Modem on server restart

### ISSUE THREAD

**Issue by krakaen** [BiggerSeries/BiggerReactors#14]
When restarting a server or a single-player world, the reactor seems to take too long(stipulation) to form and makes the modem from computercraft not detect it. This makes it that every time, you manually need to click the modem to reactivate it so that the reactor is connected.
This wasn't an issue before the 0.5.0-alpha.0

tested on 0.5.0-alpha.1

![image](https://user-images.githubusercontent.com/8230693/115965150-a4936d00-a4f5-11eb-9229-c56ee703cfbd.png)

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/BiggerReactors/commit/4bd04dee6eb3e70866d306ae165fed744da8c5ef
