### ISSUE TITLE
Unlimited power

### ISSUE THREAD

**Issue by Dabraleli** [BiggerSeries/BiggerReactors#15]
Hello!

Some info:
Modpack: All The Mods 6 1.6.2
Biggerreactors version: biggerreactors-1.16.5-0.5.0-beta.1
Mekanism: Mekanism-1.16.5-10.0.21.448

I'm not sure it's reproducable, but I'll describe:
1. Create 3x3x3 reactor;
2. Place Basic Mekanism Enery Cube;
3. Place Basic Universal Cable from Mekanism between Power Tap and Energy cube;
4. Configure it to Pull from Power Tap;
5. When inner storage is empty, energy won't stop to go to Energy Cube;

UPD: Reproduced this in creative empty world. If cable is just connected, everything fine. But if it's in pull mode, it's not even required reactor to be started ever, it just drains power from nowhere.

**Even when there is no fuel at all, just brand new reactor**

No, it's not inner storage of Cable or somehing, I took about 300-400 millions from disabled reactor and counting. 
Also in GUI I see that energy storage is being NEGATIVE and counting so on.
![image](https://user-images.githubusercontent.com/1345829/116385637-6ae29f00-a832-11eb-9163-0e43b70d073e.png)
It's already -155k/260k.

It's really strange. Am I the only one who encountered this?

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/BiggerReactors/commit/2ecb6eb391680bb742bf7377dbe04bf141c7ad43
