### ISSUE TITLE
Moderators don't seem to do anything

### ISSUE THREAD

**Issue by Yadokingu** [BiggerSeries/BiggerReactors#16]
1.16.5-0.5.0-beta.1

I have a reactor full of ludicrite blocks and yet with 90% rod insertion the reactor goes over 3000°C.
Before I had life essence in there with basically the same result.
https://imgur.com/a/uhQS2HA

**Comment by RogueLogix** [comment]
They seem to be working as expected, your reactor being hotter than you expected based on previous versions is correct behavior.

**Comment by Yadokingu** [comment]
If a reactor full of ludicrite with 90% insertion of all rods gets up to over 3000°C and ludicrite and blood don't seems to be any different from one another, you might want to rethink what you consider correct behaviour.

Or at least change the gui scale, as there basically seems to be no possible way to run the reactor within the 2000°C the gui shows.
