### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by auddie2015** [BiggerSeries/BiggerReactors#20]
Mod biggerreactors requires phosphopyllite 0.4.0 or above, and below 0.5.0. Currently is 0.5.0

0.5.0 was installed by installing Bigger Reactors. Dropping back to 0.4.5 crashes the mod.

Sorry, a version number would probably help, eh? 

Version biggerreactors-1.16.4-0.4.3.jar (Release)

**Comment by RogueLogix** [comment]
BiR 0.4.3 and Phos 0.4.5 are known to work together fine, do you have performant installed?

**Comment by auddie2015** [comment]
No performant installed. There are beta updates for BiR in the file versions though. I have CurseForge set to only update to releases so I only see them when I look for them. Since it must be something on my end, I upgraded to the latest beta and it loaded fine.

I would mark this up to something on my end.
