### ISSUE TITLE
RenderChunk rebuild coremod ConcurrentModification race condition

### ISSUE THREAD

**Issue by JakeyPrime** [BiggerSeries/BiggerReactors#24]
After building a 32 x 32 x 32 reactor, and it forming the multiblock structure, upon players loading the chunk for the first time with All The Mods 6, and now upon rejoining almost instantly, all of our clients crash. Seems to be an issue with fuel rods for some reason, and not even on the biggest reactor.

A full log of launching and error: https://paste.ee/p/F0xoM

Will happily provide any details needed but currently unless the mod is completely disabled the server is unusable.

Cheers, and great work otherwise!

**Comment by RogueLogix** [comment]
Ive seen this once before, I believe it is due to a coremod that is querying a tile entity on renderchunk rebuild, when it shouldn't be, causing the tiles to be loaded  off thread causing a race condition. It probably happens with the reactors because they are a lot of tile entities in once place, making the race condition significantly more likely, to the extent that its practically guaranteed here.

The stack trace given in the error log does not exist, so the exact calls made to cause this are impossible without a coremod, which BiR/Phos do not include.

My recommendation is to roll back the ATM6 version until it doesn't happen, if you can figure out which update causes the problem, I can investigate it further from there.

**Comment by JakeyPrime** [comment]
Sure, I'll try to make the same one in singleplayer on the same seed to repro and play around with the versioning, and see where it might have come up.

If I don't crash I'll tell you what version it is. Really sad otherwise, we'll see.

**Comment by RogueLogix** [comment]
got a helping hand from Jozufozu, who works with coremods more, try removing FramedBlocks, see if that fixes the issue, if so ill open a bug report with them to get the issue fixed

**Comment by JakeyPrime** [comment]
Hey nice! Saved me a lot of time.

Seems to be working, removed the mod from clients and server and it seems to be working so far. I'll have to get a few of us tomorrow but 2 clients seem to be fixed so far including myself.

Hopefully once your bug report is accepted ATM accepts it and hotfixes it in the next version.

**Comment by XFactHD** [comment]
Please try this test build <https://www.dropbox.com/s/1zgeemosvc61gw4/FramedBlocks-2.9.4-fixcme.jar?dl=0>. Updating the client should be enough as this is a purely client side issue. Please report back if this fixes the issue for you.

**Comment by JakeyPrime** [comment]
> Please try this test build https://www.dropbox.com/s/1zgeemosvc61gw4/FramedBlocks-2.9.4-fixcme.jar?dl=0. Updating the client should be enough as this is a purely client side issue. Please report back if this fixes the issue for you.

Apologies for the delay, server and client take forever upon relaunch, but no this didn't work.
If anything made clients crash faster upon having 3-4 fps on login. 
Seems to be the same stacktrace.

**Comment by XFactHD** [comment]
Please post the new crash report. The stacktrace can't be the same

**Comment by JakeyPrime** [comment]
> Please post the new crash report. The stacktrace can't be the same

Woops, yep, you're completely correct. I re-enabled the original mod rather than the new one, obviously getting the same error, sorry about that.

It seems to be fixed now, updated both server and client with it for fun, and it works great. 

Thanks so much for the quick work, hopefully they put the fix into the next minor version so onboarding isn't as annoying for clients on ATM6.

Cheers!

**Comment by XFactHD** [comment]
Thanks for confirming.

**Comment by XFactHD** [comment]
@JakeyPrime New version with the fix is now available on CurseForge (2.10.0).
