### ISSUE TITLE
Version 3.1 Issue

### ISSUE THREAD

**Issue by DatBigChungo** [BiggerSeries/BiggerReactors#25]
Version 3.1 is trying to use an event that has been removed from Forge (someone else said this). I got a crash report when trying to use it. Here is the report: https://forums.minecraftforge.net/topic/104192-solved-error-when-opening-minecraft-with-atm7-1171-modpack/

**Comment by RogueLogix** [comment]
alpha.3.1 fixed this issues, you are using alpha.2 there.
