### ISSUE TITLE
[1.17.1] Uranium Ore does not generate in world.

### ISSUE THREAD

**Issue by Gbergz** [BiggerSeries/BiggerReactors#26]
Been flying around in spectator mode & I've used a scanner from the Mod scanner to search only for the block. 
It's nowhere to be found. I'm guessing this is an issue so iI'll report it.

### Versions:
**Minecraft**: 1.17.1
**Forge**: 37.0.53
**Bigger Reactors**: 0.6.0-alpha.3.1 | https://www.curseforge.com/minecraft/mc-mods/biggerreactors/files/3448811
**Phosphophyllite**: 0.6.0-alpha.3 | https://www.curseforge.com/minecraft/mc-mods/phosphophyllite/files/3447790

### More:
I did this on a clean instance with no mods installed other than **Bigger Reactors & Phosphophyllite** and the same result is present there. No Uranium Ore.

**-** Gbergz

**Comment by RogueLogix** [comment]
Registry issue, there was a small log error about it, but logging is kinda broken in 1.17 still, so i missed it
`[18:48:56] [Worker-Main-8/ERROR]: Cannot register unknown block for world generation`
