### ISSUE TITLE
1.17.1 Right Click on Casing Creates Error

### ISSUE THREAD

**Issue by Ocraftyone** [BiggerSeries/BiggerReactors#28]
In All the Mods 7, if you right click on a block that doesn't have a GUI after the reactor has be built, the block detaches and says unknown error. Just seems like you need to add something saying if the block is part of a built reactor multiblock, don't do anything.

Edit: the blocks get fixed after rebuilding the reactor, also discovered that this prevents you from using the reactor control rods

Just built reactor, nothing done:
![image](https://user-images.githubusercontent.com/24759591/135218739-7bcd4c98-a165-4c43-b88f-d8409b2f37a2.png)

After right clicking a reactor casing (Notice the error in chat):
![image](https://user-images.githubusercontent.com/24759591/135218780-c52ac058-c92e-48dd-94e9-c22e1f06c47c.png)

**Comment by Ocraftyone** [comment]
This did not fix it. It now crashes the game/server whenever you create a reactor

**Comment by Ocraftyone** [comment]
Currently working on implementing that. I'll let you know what the result is

**Comment by RogueLogix** [comment]
another fresh jar, should fix that issue (and similar ones that may have happened if that specific one didn't) https://github.com/BiggerSeries/BiggerReactors/suites/4015229238/artifacts/101403485

**Comment by RogueLogix** [comment]
you appear to have a version mismatch there, attempting to load with BiR alpha 5 and Phos alpha 4
you will need both of the new files linked here
