### ISSUE TITLE
Uranium Ore breaks instantly, and without tools

### ISSUE THREAD

**Issue by lamoyrl90** [BiggerSeries/BiggerReactors#29]
biggerreactors-1.18.1-0.6.0-alpha.9
Minecraft 1.18.1
Forge 39.0.0

**Comment by Gbergz** [comment]
can confirm

**Comment by RogueLogix** [comment]
known but low priority issue, in most cases the ore gen is turned off and as a result this doesn't matter. Correcting how the blocks are mined in general has been needed since 1.16, as all blocks are fist mineable iirc.
