### ISSUE TITLE
Reactors that are larger than a Chunk stop being a multiblock on server reboot

### ISSUE THREAD

**Issue by sarr95** [BiggerSeries/BiggerReactors#32]
i have a 25x25x8 reactor and every time i reboot my server it stops being a multiblock. saying that a fuel rod is in the wrong spot when it was working before the reboot. i am only able to fix the issue by using world edit to replace the entire reactor i have not changed any settings. if you want a log please tell me where to find said log

**Comment by RogueLogix** [comment]
What version are you using?

**Comment by sarr95** [comment]
biggerreactors-1.18-0.6.0-alpha.8.1 forge

**Comment by RogueLogix** [comment]
This issue should already be fixed in 1.18.1-0.6.0-alpha.9.1

**Comment by sarr95** [comment]
yes but that does not help because it is 1.18.1 not 1.18

**Comment by RogueLogix** [comment]
then, update?

**Comment by sarr95** [comment]
i see this is going to go nowhere so never mind i cant just update because not all mods my server is using can be

**Comment by RogueLogix** [comment]
im going to close this, if its still an issue after you update, you can open a new issue
