### ISSUE TITLE
Cyanite reprocessor has no gui config and does not accept water from any sides

### ISSUE THREAD

**Issue by theArhar** [BiggerSeries/BiggerReactors#37]
Minecraft version: 1.16.5
Mod version: 0.5.1
Minecraft Forge version: 36.2.22
Mod Pack: TNP Limitless 3 1.11.7

https://imgur.com/a/fO0xrM5

**Comment by theArhar** [comment]
also it maybe a mekanism infinite water tank bug, it accepts water if i pump it in

**Comment by RogueLogix** [comment]
Mechanism tanks push water into the cyanite reprocessor correctly when tested.

**Comment by RogueLogix** [comment]
also, all sides on the re-processor serve all functions, making a side configuration unneeded.
