### ISSUE TITLE
Bigger Reactors and Forbidden Arcanus Crash

### ISSUE THREAD

**Issue by Tomatoh** [BiggerSeries/BiggerReactors#38]
Tracked down a crash at world creation in single player and multiplayer stating that

com.google.gson.JsonParseException: Error loading registry data: Unknown tag: forbidden_arcanus:darkstone_ore_replaceables

The crash is between forbidden_arcanus-1.18.1-2.0.1.jar and biggerreactors-1.18.1-0.6.0-beta.jar

ruled out valhelsia_core-1.18.1-0.3.1.jar (forbidden arcus), quartz-1.18.1-0.0.0-beta.jar (bigger reactors), and phosphophyllite-1.18.1-0.6.0-beta.jar (bigger reactors)

Definitely reproducable by just loading those 5 files

https://github.com/stal111/Forbidden-Arcanus/issues/233

**Comment by lukiono** [comment]
Greetings, 

can confirm this issue. heres my log;
https://mclo.gs/86yJj0V

**Comment by RogueLogix** [comment]
closing with [stal111/Forbidden-Arcanus#233](https://github.com/stal111/Forbidden-Arcanus/issues/233#issuecomment-1026215301)
