### ISSUE TITLE
An unknown error to report

### ISSUE THREAD

**Issue by thmarinho** [BiggerSeries/BiggerReactors#39]
Hello,
I'm trying to build a new reactor ( 9*6*7 ) on my ATM7 server, the structure is detected as invalid and the  `An unknown multiblock error has occurred, report to mod author` error appears.
Any ideas ? 
Screens available bellows

## Front
![2022-01-22_18 56 31](https://user-images.githubusercontent.com/40118153/150650127-3bf71e79-1474-428a-80ec-24c7b70dab4a.png)

## Top
![2022-01-22_18 56 34](https://user-images.githubusercontent.com/40118153/150650139-e5d7c115-54e6-4077-9643-722613cf1de2.png)

## Back
![2022-01-22_18 56 40](https://user-images.githubusercontent.com/40118153/150650147-26cfdb21-e47c-49a3-8208-32661ec1b383.png)

## Bottom
![2022-01-22_18 56 47](https://user-images.githubusercontent.com/40118153/150650153-867a293c-73e8-407a-ba78-627ab3ebe443.png)

**Comment by thmarinho** [comment]
I've just rebuild a 7x7x7, on click on the terminal, dimensions are retrieved as 1x1x1

**Comment by RogueLogix** [comment]
What mod version?

**Comment by thmarinho** [comment]
biggerreactors-1.18.1-0.6.0-beta.jar

**Comment by RogueLogix** [comment]
Phos 0.6.0-beta.0.1 had some multiblock related fixes in it, which may fix your issue

**Comment by RogueLogix** [comment]
likely fixed by https://github.com/BiggerSeries/Phosphophyllite/commit/db9b88def4316c06d66b9fe5494d152d7271fe79 if not fixed earlier in beta.0.1, ive also been unable to reproduce this specific issue, so, ill be closing it
