### ISSUE TITLE
Translate ru_ru 1.16.5

### ISSUE THREAD

**Issue by BazZziliuS** [BiggerSeries/BiggerReactors#42]
I have translated your mod into Russian. Add it in future releases <3

https://pastebin.com/raw/aEQpvhdc

**Comment by RogueLogix** [comment]
Closing because even the English lang file has been lacking for this entire time, and has only gotten worse. While I'm not opposed to translations, infrequent PRs to specific languages isn't a sustainable solution. Something like Crowdin needs to be a regular part of the release cycle.
