### ISSUE TITLE
Invisibility bug with optifine

### ISSUE THREAD

**Issue by Pattaa** [BiggerSeries/BiggerReactors#43]
Hey guys, after some while my hand, mobs, players and blocks on the ground disappears when playing with optifine. They are still there but simply can't be seen. This bug usually happens when moving through the nether portal. Any idea why this is happening (except the fact I'm using optifine)?

**Comment by RogueLogix** [comment]
If you can reproduce it without optifine, I would be more than happy to look into it, but if it only happens with optifine then it isn't an issue i am going to fix
