### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ouroborus** [BiggerSeries/BiggerReactors#47]
The [website](https://biggerseries.net/biggerreactors) says Bigger Reactors is licensed under LGPL 2.1.

I recommend adding a license file to the repo.

One way to do this would be to copy [lgpl-2.1.md](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.md) to `LICENSE.md`.

See also: [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by ouroborus** [comment]
https://github.com/BiggerSeries/Phosphophyllite/issues/21

**Comment by RogueLogix** [comment]
it exists, its just not at the repo root, this becomes jar root at build
https://github.com/BiggerSeries/BiggerReactors/blob/master/src/main/resources/LICENSE.txt
