### ISSUE TITLE
Multi block not completing

### ISSUE THREAD

**Issue by Dragonlord1005** [BiggerSeries/BiggerReactors#5]
Whenever I make a reactor sometimes, it’ll say that all fuel elements must extend from the top of the reactor to the bottom then gives me some coordinates, so I go to those coordinates and there are no fuel cells or control cells there, it always happens right inside the reactor and I can’t seem to fix it

**Comment by RogueLogix** [comment]
A fuel element is a column of fuel rods topped by a control rod. It is giving you that error because there is (or it thinks there is) a control rod above those coordinates and its checking for the fuel rods.

**Comment by Dragonlord1005** [comment]
Ok, I’ll check

**Comment by Dragonlord1005** [comment]
So umm I don’t know what happened, but my game crashed (its a completely seperate thing) and I reloaded the world and the reactor is there as a multiblock, so I don’t know what happened but it’s fixed now
