### ISSUE TITLE
Reactor Terminal JEI Feature missing from 1.18

### ISSUE THREAD

**Issue by TheRealArchie** [BiggerSeries/BiggerReactors#50]
The Reactor Terminal JEI Feature is missing from 1.18 Bigger Reactors, where it showed possible coolants and such. Please add it. Thank you.

**Comment by IAmInept** [comment]
In addition to this, the same issue is occurring with 1.16.5 (ATM6)

**Comment by RogueLogix** [comment]
1.16 has a different non-fixable issue with multiplayer, that presents itself in the same way.

**Comment by RogueLogix** [comment]
This didn't auto-close because 1.19 isn't the main branch, but this has been fixed for a while now.
