### ISSUE TITLE
CC, Advanced Peripherls integration

### ISSUE THREAD

**Issue by gamenTV** [BiggerSeries/BiggerReactors#55]
Integration for Reactor Exhaust Tank

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/BiggerReactors/blob/05c73ae7239cb60f7feea6c5215b97b610924f3a/src/main/java/net/roguelogix/biggerreactors/multiblocks/reactor/deps/ReactorPeripheral.java#L136-L140
