### ISSUE TITLE
Reactor voiding fuel when joining world 

### ISSUE THREAD

**Issue by stone11062006** [BiggerSeries/BiggerReactors#64]
Hello, I'm playing in a survival world in solo on the modpack All The Mod 6, which contain bigger reactor, and every time I log in my world, my reator is empty, even if it was full when i left. In addition, the reactor is also turned of when i join

**Comment by RogueLogix** [comment]
if you still have the world, can you provide a screenshot of the top of your reactor with F3 open and chunk boundaries shown.

**Comment by Hevoc44** [comment]
ich gehe davon aus das der reaktor beim chunk laaden sich automatisch entleert und nichts drinne schpeichert

**Comment by dredgemage** [comment]
Running an All The Mods 8 server and also having this issue. I've attached a screenshot and will see if I can replicate it in singleplayer with no other mods.
![2023-01-24_21 42 01](https://user-images.githubusercontent.com/6761184/214475266-ad50682e-01f0-4d35-97cd-ea636d1f453f.png)

**Comment by RogueLogix** [comment]
for ATM8, assuming version 1.0.7 or higher, please create a new issue, there were enough changes between 1.16 and 1.19 that its extremely unlikely that this is the same issue
