### ISSUE TITLE
Bigger Reactor timeouts server on max size 128x128x192

### ISSUE THREAD

**Issue by torbenprobst** [BiggerSeries/BiggerReactors#66]
# Infos
Server ist running ATM7 0.4.34

# Problem:
A friend of mine built a Bigger Reactor with the max size of 128x128x192.
As soon as everything were built and placed the server suddenly began to timeout and crash all the time.

Sometimes after 15 mins but often much earlier.

If you need further informations hit me up.

Following parts were used in the max version of the Multiblock Reactor:
- rods
- casing
- control rods
-  controller
-  2x access ports
- powertap

### Crash Log: 
https://mclo.gs/fTIK5l8

### Picture of the Reactor
This is how the reactor looks like:
![image](https://user-images.githubusercontent.com/46575728/200776723-756160db-6282-47a1-8188-8047d71212e5.png)

**Comment by RogueLogix** [comment]
For future knowledge, issues can be transferred.

The crash log you have is a watchdog kill and not a crash from my code, based on the log its being killed while merging multiblocks. the watchdog should be disabled, im not sure how exactly thats done, but google should find it for you.
this circumstance is also most likely to happen at chunk load/unload, so add a chunkloader if you can to reduce multiblock operations.

**Comment by RogueLogix** [comment]
Closing as stale without specific crash, open a new issue if this still persists
