### ISSUE TITLE
I cant play bigger reactors with my friend

### ISSUE THREAD

**Issue by dinospino779** [BiggerSeries/BiggerReactors#73]
Me and my friend due to the circunstances we cannot play in the most recent forge version we are in 40.1.76.

**Comment by RogueLogix** [comment]
![image](https://user-images.githubusercontent.com/9971693/218241579-0cfd4c2c-3c5d-45d2-a2ac-b4de903b28ef.png)

I'll need more details on your issue.

**Comment by dinospino779** [comment]
That we need the most recent version of bigger reactors but me snd my friend have forge version in 40.1.76 and the mod requires forge 40.2.0

**Comment by dinospino779** [comment]
No problem i already fix it!
