### ISSUE TITLE
Reactor fuel dump and Reactor shutdown on server reset

### ISSUE THREAD

**Issue by IWenton** [BiggerSeries/BiggerReactors#78]
Currently using a 13x7x9 (LxWxH exterior) reactor on a ATM 8 server hosted by g-portal, it is placed inside of a Maximum compact machine and chunk loaded via ftbchunks. I am also using computer craft to control the reactor (this does not seem to be a factor). After every server reset, any fuel in my reactor gets voided and the reactor is turned off. I'm currently mitigating the fuel issue by overproducing uranium with other mods. I have no idea how to keep my reactor from turning off.

**Comment by RogueLogix** [comment]
duplicate of #71

**Comment by IWenton** [comment]
Fuel dump only happens on server reset and not world join
