### ISSUE TITLE
Actively cooled reactor not outputting steam

### ISSUE THREAD

**Issue by TrickShotMLG02** [BiggerSeries/BiggerReactors#79]
I built a reactor and everything worked fine. I built a turbine, removed the powertap from the reactor and added 2 coolant ports. One for input and one for output. I hooked the reactor up to the turbine and started the reactor. after a short time i noticed that my turbine didn't produce any energy. I found out that my turbine doesn't get steam from the reactor.

My Reactor terminal looks like the following:
https://youtu.be/odGqLY3yggQ

modpack: atm8 1.19.2

**Comment by RogueLogix** [comment]
should be fixed by this in the next mod version https://github.com/BiggerSeries/BiggerReactors/commit/34b429be62fecbb119d22731f6aad633ad5aec8f and https://github.com/BiggerSeries/Phosphophyllite/issues/30, reopen if it isn't.
