### ISSUE TITLE
Aktivcooling reactor is extremely hot

### ISSUE THREAD

**Issue by Hevoc44** [BiggerSeries/BiggerReactors#80]
My aktive cooling Reaktor is at the moment too hot its over 5000000k heat and won't get down I had a Redstone port and set it up. The reactor shut down at 90k heat but he gets even hotter than I was set it up. And I won't the water ore stem in it its 1.19. The reactor is big and the turbine too the turben generates 7.6 million rf and gets steam but it don't exist stem in the reaktor

**Comment by RogueLogix** [comment]
Active reactors are supposed to overheat if not cooled properly, such as too low steam flow. This sounds like intended behavior
