### ISSUE TITLE
Multiblock causes crash even if reactor was not activated

### ISSUE THREAD

**Issue by Phaxyy** [BiggerSeries/BiggerReactors#82]
I placed the multiblock, it was a 5x4 reactor i think. Then i almost build everything together and placed the reactor terminal above the power tap. Then the multiblock reacted and gave me a error code while accesisng the panel, then i broke the block and then the whole server crashed, and now the server cannot start anymore.

[crash-2023-04-18_06.22.37-server.txt](https://github.com/BiggerSeries/BiggerReactors/files/11258692/crash-2023-04-18_06.22.37-server.txt)
[crash-2023-04-18_06.33.20-server.txt](https://github.com/BiggerSeries/BiggerReactors/files/11258693/crash-2023-04-18_06.33.20-server.txt)

Thank you for the support best regards

**Comment by RogueLogix** [comment]
This crash has been seen before, but its extremely hard to reproduce. given that this was never bumped i assume it never happened again, which is typical for this bug. If this happens to you again, or anyone else, open a new issue, and try and find a way to reliably reproduce it so i can finally fix it.
