### ISSUE TITLE
The ReactorPowerTapTile exposes the wrong capability

### ISSUE THREAD

**Issue by agnor99** [BiggerSeries/BiggerReactors#84]
When queried for the Forge Energy Capability the ReactorPowerTapTile returns itself which doesn't implement IEnergyStorage, causes ClassCastExceptions when trying to resolve this LazyOptional.
This happens with EnderIO and with Pipez:
This is the crash that happened with EnderIO: https://paste.ubuntu.com/p/3rmBJvXwH9/

**Comment by RogueLogix** [comment]
yay forgetting some code removal...
