### ISSUE TITLE
the mod is Causing the game to crash 

### ISSUE THREAD

**Issue by xXshadowWolf** [BiggerSeries/BiggerReactors#88]
the mod is Causing the game to crash can you please fix it
[debug.log](https://github.com/BiggerSeries/BiggerReactors/files/12388473/debug.log)
[JadeErrorOutput.txt](https://github.com/BiggerSeries/BiggerReactors/files/12388474/JadeErrorOutput.txt)
[latest.log](https://github.com/BiggerSeries/BiggerReactors/files/12388475/latest.log)
[crash-2023-08-20_10.00.17-client.txt](https://github.com/BiggerSeries/BiggerReactors/files/12388477/crash-2023-08-20_10.00.17-client.txt)

**Comment by RogueLogix** [comment]
was fixed in 1340c3fbeb5c4ee6d6831ef7c652d84f4318a2ea
