### ISSUE TITLE
Faster way to process cyanite ingot into blutonium

### ISSUE THREAD

**Issue by DarkShadow012** [BiggerSeries/BiggerReactors#89]
Is there a faster way ? im playing on TNP Limitless 6.
Like can you add a reprocessor that store more ingots like the machines from mekanism?and upgrades for that to make it faster and more efficient?

**Comment by RogueLogix** [comment]
Just use multiple? Even quite large reactors should only need a small handful at most for steady state operation, and they aren't particularly costly to run in the first place. If you want to change its though there are config options for basically everything.
