### ISSUE TITLE
the mod's turbine rotors are not rotating

### ISSUE THREAD

**Issue by kaelhub** [BiggerSeries/BiggerReactors#97]
![image](https://github.com/BiggerSeries/BiggerReactors/assets/95586113/e7722ace-7fe1-41d8-b206-c97cb28277bd)

the mod's turbine rotors are not rotating even though there is steam in it

**Comment by RogueLogix** [comment]
what version?

**Comment by kaelhub** [comment]
1.18.2, Do you want me to send the logs? I think it's a conflict with another mod

**Comment by RogueLogix** [comment]
Oh, I failed to notice, you have the flow rate set to zero, this is correct behavior. Use the arrows to increase the steam flow rate limit.

**Comment by kaelhub** [comment]
oh my god how did I not realize that
